### ISSUE TITLE
Repo don't work

### ISSUE THREAD

**Issue by Oyo95** [Kuschel-code/JellyfinUpscalerPlugin#1]
Hi,

I have tried to use this plugin but when i add the URL for installing it, it doesn't appear in the catalog.

**Comment by mitch030504** [comment]
i am suffering from the same issue

**Comment by Kuschel-code** [comment]
I'll continue working on it tomorrow. I'm unfortunately aware of the problem and will try to fix it then

**Comment by michael-zock** [comment]
Thanks in advance for looking into it.

**Comment by Kuschel-code** [comment]
Update: I have fixed the issue, so the plugin is now displayed in the catalog. I am continuing to work on further improvements.

**Comment by michael-zock** [comment]
@Kuschel-code Thanks, though it's not quite the progress I expected (10.10.3 on Win 11 Pro with all the latest updates).
```
[2024-11-30 21:32:24.113 +01:00] [ERR] [126] Emby.Server.Implementations.Updates.InstallationManager: The checksums didn't match while installing "Jellyfin Upscaler", expected: "SHA256:F81E92F9D70ED06771E402D37D4C14BAD1B39C44CFB32435FD5622EDACB6EBCC", got: "40DD52157A6B002F9671C0AE64C0EF15"
[2024-11-30 21:32:24.115 +01:00] [ERR] [126] Emby.Server.Implementations.Updates.InstallationManager: Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
[2024-11-30 21:32:24.125 +01:00] [ERR] [126] Jellyfin.Api.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/Packages/Installed/Jellyfin%20Upscaler".
System.IO.InvalidDataException: The checksum of the received data doesn't match.
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   at Jellyfin.Api.Controllers.PackageController.InstallPackage(String name, Nullable`1 assemblyGuid, String version, String repositoryUrl)
   at lambda_method2404(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Jellyfin.Api.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Api.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Api.Middleware.IPBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Api.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Api.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Api.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Api.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Api.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2024-11-30 21:32:39.896 +01:00] [INF] [106] Emby.Server.Implementations.IO.LibraryMonitor: "Specials" ("H:\Video\Battlestar Galactica (2004) [tmdbid-1972] [imdbid-tt0407362]\S00") will be refreshed.
[2024-11-30 21:32:39.911 +01:00] [INF] [102] Emby.Server.Implementations.IO.LibraryMonitor: "Battlestar Galactica (2004) [tmdbid-1972] [imdbid-tt0407362]" ("I:\Video\Battlestar Galactica\Battlestar Galactica (2004) [tmdbid-1972] [imdbid-tt0407362]") will be refreshed.
[2024-11-30 21:32:39.918 +01:00] [INF] [3] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"I:\Video\Battlestar Galactica\Battlestar Galactica (2004) [tmdbid-1972] [imdbid-tt0407362]\S00\Battlestar Galactica (2003) - Blood & Chrome.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-11-30 21:32:39.960 +01:00] [ERR] [106] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "Probe Provider"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)

```

**Comment by Kuschel-code** [comment]
I am still working on the rest. This should just be an interim update, as I am already aware of the errors. c:

**Comment by Kuschel-code** [comment]
UpdateFunctions:

AI Upscaling:
Uses models like ESRGAN and Waifu2x to enhance video quality, with the ability to upscale resolution up to 8K.

Automatic Library Recognition:
Adjusts settings based on library types such as Anime, Movies, or TV Shows.

Custom Profiles:
Create personalized profiles with settings for FPS, resolution, sharpness, saturation, contrast, and noise reduction.

Benchmark Test:
Automatically or manually checks whether your device supports AI upscaling.

Traditional Shaders:
Uses shaders like Bicubic, Bilinear, or Lanczos for devices with limited performance.

Finalization Notice:
To finalize the plugin, some important points are still missing, and it will be replaced in the next three days.

**Comment by khostri** [comment]
Hi,
tried plugin yesterday on my docker stack - unpacked and put into plugin directory, but plugin is not visible after restart. Strange thing for me is that all other plugins have *.dll, but here is just json, *.js and in *.bin (in shaders folder). No dll.
My stack can work with external plugins as I have already added SSO plugin for authentik and it works normally.
Checked docker logs, but plugin is not even parsed on restart.

**Comment by Druidblack** [comment]
How do I install the plugin? Using manifest.json or manual copying does not produce results.
